# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb0ba50453fcf4138e22dbc858100a4e82772f00c46da7d4bf2d3138003d28e93b0fdc79618e041ff4d0eb123c8a4705f9c9d25bd9fdb1562c78cfb2f4469009

test:
  secret_key_base: c0e20011fa2059cbe06cd9f7c8638162241153ea8544d199253bc2d2e560206bc218250d64079e4fdcb12d50a43a66fea01ec32fe5dd9eec23cf4e857f4f8a53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
